# List all environments in use
environments:
  - development
  - test
  - production

# Choose environment
environment: production

# Paths (relative to ./controllers) to the views and public folders
views_path:  '../views'
public_path: '../public'

# Development specific settings
development:
  sqlite_path: 'database/liberta.db'
