# Paths (relative to ./controllers) to the views and public folders
views_path: &views_path '../views'
public_path: &public_path '../public'

migrations_path: &migrations_path './database/migrations'

# Development specific settings
development:
  sqlite_path: 'database/liberta.db'
  views_path: *views_path
  public_path: *public_path
  migrations_path: *migrations_path

test:
  views_path: *views_path
  public_path: *public_path
  migrations_path: *migrations_path

production:
  db_host: 'localhost'
  db_name: 'liberta'
  db_user: 'liberta'
  db_password: 'liberta'
  views_path: *views_path
  public_path: *public_path
  migrations_path: *migrations_path
