# List all environments in use
environments:
  - development
  - test
  - production

# Choose environment
environment: production

# Paths (relative to ./controllers) to the views and public folders
views_path:      '../views'
public_path:     '../public'
migrations_path: './database/migrations'

# Development specific settings
development:
  sqlite_path: 'database/liberta.db'

production:
  db_server: 'localhost'
  db_name:   'liberta'
  db_user:   'liberta'
  db_pass:   'liberta'
